#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

admin=$YNH_APP_ARG_ADMIN
port=$YNH_APP_ARG_PORT

app=$YNH_APP_INSTANCE_NAME

ynh_script_progression --message="Ok" --time --weight=1

ynh_script_progression --message="Installation of $app completed" --last
